
services:

  ros:
    # stdin_open: true
    # tty: true

    image: 'ros:noetic-ros-base-focal'
    network_mode: 'host'
    environment:
      - ROS_MASTER_URI=http://192.168.51.28:11311/
      - ROS_IP=192.168.51.28
    
    volumes:
      - /home/pi/minesweeper-ros-backend/ros_nodes/keyboard_node/
      - /home/pi/minesweeper-ros-backend/

    command: 'roscore'
    
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
      - "11311:11311"
    
    build:
      context: .
      dockerfile: Dockerfile
