frequency: 50
# Update frequency in Hz
sensor_timeout: 0.1
# Timeout for sensor data
# World frame (global frame for localization)
map_frame: map
odom_frame: odom
base_link_frame: base_link
two_d_mode: true
# Robot's body frame
# Use 2D localization (x, y, and yaw only)
# Process noise covariance
process_noise_covariance: [0.05, 0,0,0, 0.05, 0,0, 0,0.01]
# IMU configuration
imu0: /imu/data
imu0_config: [false, false, false,false, false, true, 
false, false, false, 
false, false, true, 
false, false, false]
imu0_differential: false
imu0_relative: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
# Odometry configuration
odom0: /odom
odom0_config: [true, true, false,
false, false, true, 
true, true, false, 
false, false, false]
odom0_differential: false
odom0_relative: true
odom0_queue_size: 10